stages:
  - build
  - sonarqube

variables:
  SONAR_HOST_URL: "https://sonarcloud.io"  # Or your self-hosted SonarQube URL
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_NOLOGO: "true"

cache:
  paths:
    - ~/.nuget/packages

before_script:
  - dotnet --version

build:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Release
    - dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory coverage

sonarqube-check:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: sonarqube
  script:
    # Install dotnet-sonarscanner as a global tool
    - dotnet tool install --global dotnet-sonarscanner
    - export PATH="$PATH:$HOME/.dotnet/tools"
    # Start analysis
    - dotnet sonarscanner begin /k:"$CI_PROJECT_NAME" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN"
    - dotnet build --configuration Release
    - dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory coverage
    # Complete analysis
    - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
  only:
    - main
    - master
