stages:
  - build
  - sonarqube

variables:
  SONAR_HOST_URL: "https://sonarcloud.io" # Or your self-hosted SonarQube server

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - ./gradlew --version

build:
  image: gradle:8.5-jdk17
  stage: build
  script:
    - ./gradlew clean build jacocoTestReport

sonarqube-check:
  image: gradle:8.5-jdk17
  stage: sonarqube
  script:
    - ./gradlew sonarqube
      -Dsonar.projectKey=$CI_PROJECT_NAME
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
  only:
    - main
    - master
